---
driver:
  name: docker

provisioner:
  name: chef_zero
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'

platforms:
- name: ubuntu-12.04
- name: centos-6

suites:
- name: default
  run_list: ["recipe[hello_world_circleci_deploy_example]"]
