name 'hello_world_circleci_deploy_example'
maintainer 'Mike Splain'
maintainer_email 'mike.splain@gmail.com'
license 'All rights reserved'
description 'Installs/Configures hello_world_circleci_deploy_example'
long_description 'Installs/Configures hello_world_circleci_deploy_example'
version '0.1.0'

depends 'apt'
depends 'apache2'
depends 'yum-epel'
depends 'yum-centos'
depends 'yum'
