name             'hello_world_circleci_deploy_example'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures hello_world_circleci_deploy_example'
long_description 'Installs/Configures hello_world_circleci_deploy_example'
version          '0.1.0'
